// AllKey.ts
const AllKey: string[] = [
  "School Management System",
  "School Software",
  "Student Information System",
  "Educational Management Software",
  "Online School Management",
  "School Administration Software",
  "School ERP System",
  "Academic Management System",
  "Cloud-Based School Management",
  "Web-Based School Software",
  "Student Database Management",
  "Attendance Management System",
  "Fee Management Software",
  "Examination Management System",
  "Gradebook Software",
  "Timetable Management System",
  "Library Management Software",
  "Parent Portal System",
  "Teacher Dashboard",
  "Learning Management System (LMS)",
  "School Communication Platform",
  "Online Admission Management",
  "School Scheduling Software",
  "Staff Management System",
  "Virtual Classroom Platform",
  "Mobile School Management App",
  "Student Performance Tracking",
  "Online Exam Software",
  "School Fee Collection System",
  "Integrated School Solution",
  "School Record Management",
  "Student Enrollment Software",
  "Curriculum Management System",
  "School Finance Management",
  "School Inventory System",
  "Academic Calendar Software",
  "Student Health Management",
  "Parent-Teacher Communication",
  "Report Card Generator",
  "Hostel Management System",
  "Alumni Management Software",
  "Student ID Card Generation",
  "Online Learning Platform",
  "School Security Management",
  "Online Grading System",
  "Student Progress Tracking",
  "School Event Management",
  "Student Feedback System",
  "School Transport Management",
  "School Website Development",
  "Unified School Platform",
  "Student Behavior Tracking",
  "School Data Analytics",
  "Admission Enquiry Management",
  "Online Fee Payment Gateway",
  "Student Dormitory Management",
  "School Document Management",
  "Student Information Portal",
  "Exam Result Processing",
  "Teacher Evaluation System",
  "School Newsletter Software",
  "Student Certificate Generation",
  "School Asset Management",
  "Interactive Classroom Tools",
  "Online Homework Submission",
  "School Calendar Planner",
  "School Resource Allocation",
  "Online Course Registration",
  "Student Counseling System",
  "School Health Records",
  "Digital Learning Resources",
  "School Incident Reporting",
  "Online Parent Workshops",
  "Student Competency Tracking",
  "School Performance Analysis",
  "School Budget Planning",
  "Student Absence Management",
  "School Community Engagement",
  "Online Student Feedback",
  "Student Portfolio Management",
  "School Collaboration Tools",
  "Student Group Management",
  "School Infrastructure Mapping",
  "School Assessment Tools",
  "Student Assessment Reports",
  "Online Skill Assessment",
  "School Crisis Management",
  "Student Scholarships Management",
  "School Accreditation Software",
  "Student Placement Services",
  "School Resource Booking",
  "Student Self-Service Portal",
  "School Vendor Management",
  "Student Discipline Management",
  "School Data Security Measures",
  "Student Grievance Redressal",
  "School Learning Analytics",
  "Student Mentoring Programs",
  "School Virtual Tour",
  "Student Achievement Recognition"
];

export default AllKey;
